# requirements.yaml
dependencies:
  - alias: blockchain-prod-1
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchain
      - main
      - minimal
  - alias: blockchain-prod-2
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchainSecond
      - main
  - alias: blockchain-test-1
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchain
      - main
      - minimal
  - alias: blockchain-test-2
    name: blockchain
    version: "0.1.0"
    repository: file://../blockchain
    tags:
      - blockchainSecond
      - main
  - alias: api-prod-1
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - api
      - main
      - minimal
  - alias: api-prod-2
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - apiSecond
      - main
  - alias: api-test-1
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - api
      - main
      - minimal
  - alias: api-test-2
    name: api
    version: "0.1.0"
    repository: file://../api
    tags:
      - apiSecond
      - main
  - alias: frontend-1
    name: frontend
    version: "0.1.0"
    repository: file://../frontend
    tags:
      - frontend
      - main
      - minimal
  - alias: frontend-2
    name: frontend
    version: "0.1.0"
    repository: file://../frontend
    tags:
      - frontendSecond
      - main
  - alias: excel-export-1
    name: excel-export
    version: "0.1.0"
    repository: file://../excel-export
    tags:
      - excel-export
      - main
      - minimal
