version: "3"

services:
  master-node:
    build: ../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      NODE_ENV: ${NODE_ENV}
      CERT_PATH: ${CERT_PATH}
      CERT_CA_PATH: ${CERT_CA_PATH}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
    # volume for persisting data from multichain
    volumes:
      - ~/masterVolume:/root/.multichain
    ports:
      - ${RPC_PORT}:${RPC_PORT} # port for connecting API
      - "8085:8085" # port for backup
      - "7447:7447" # port for connecting slaves (P2P)

  master-api:
    build: ../api
    environment:
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      DOCUMENT_FEATURE_ENABLED: ${DOCUMENT_FEATURE_ENABLED}
      STORAGE_SERVICE_EXTERNAL_URL: ${STORAGE_SERVICE_EXTERNAL_URL}
      STORAGE_SERVICE_HOST: storage-service
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      ORGANIZATION_PUBLIC_KEY: ${ORGANIZATION_PUBLIC_KEY}
      ORGANIZATION_PRIVATE_KEY: ${ORGANIZATION_PRIVATE_KEY}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SIGNING_METHOD: ${SIGNING_METHOD}
      NODE_ENV: ${NODE_ENV}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      LOG_LEVEL: ${API_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    command: ["npm", "run", "watch"] # npm run watch: hot reloading
    # volume to track code changes
    volumes:
      - "../api/src:/home/node/src:delegated"
      - ../api/dist:/home/node/dist
    depends_on:
      - master-node
    ports:
      - ${API_PORT}:${API_PORT}


  provisioning:
    build:
      context: ../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: TEST
      #Other provisioning data:
      #ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
      LOG_LEVEL: ${PROVISIONING_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    # volumes:
    #   - "../../provisioning/src:/usr/src/app/src:delegated"
    depends_on:
      - master-api
