version: "3"
services:
  blockchain:
    build: .
    environment:
      PORT: 8085
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      MULTICHAIN_FEED: ${MULTICHAIN_FEED}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      NODE_ENV: ${NODE_ENV}
      CERT_PATH: ${CERT_PATH}
      CERT_CA_PATH: ${CERT_CA_PATH}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
    ports:
      - ${RPC_PORT}:${RPC_PORT} # port for connecting API
      - "8085:8085" # port for backup
      - "7447:7447" # port for connecting slaves (P2P)


