version: "3"
services:
  api:
    extends:
      file: api/docker-compose.yml
      service: api
    build: ../api
    image: docker-compose-api:local
    command: [ "npm", "run", "watch" ]
    volumes:
      - "../api/src:/home/node/src:delegated"
      - ../api/dist:/home/node/dist
