services:
  blockchain:
    image: trubudget/blockchain:${TAG}
    environment:
      PORT: ${BLOCKCHAIN_PORT}
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      RPC_ALLOW_IP: ${RPC_ALLOW_IP}
      RPC_USER: ${RPC_USER}
      ORGANIZATION: ${ORGANIZATION}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      NODE_ENV: ${ENVIRONMENT}
      CERT_PATH: ${CERT_PATH}
      CERT_CA_PATH: ${CERT_CA_PATH}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
      BLOCKNOTIFY_SCRIPT: ${BLOCKNOTIFY_SCRIPT}
      KUBE_SERVICE_NAME: ${KUBE_SERVICE_NAME}
      KUBE_NAMESPACE: ${KUBE_NAMESPACE}
      EXPOSE_MC: ${EXPOSE_MC}
      CI_COMMIT_SHA: ${CI_COMMIT_SHA}
      BUILDTIMESTAMP: ${BUILDTIMESTAMP}
      EXTERNAL_IP: ${EXTERNAL_IP}
      P2P_HOST: ${P2P_HOST}
      P2P_PORT: ${P2P_PORT}
      API_PROTO: ${API_PROTO}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      MULTICHAIN_DIR: ${MULTICHAIN_DIR}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SSL: ${EMAIL_SSL}
      NOTIFICATION_PATH: ${NOTIFICATION_PATH}
      NOTIFICATION_MAX_LIFETIME: ${NOTIFICATION_MAX_LIFETIME}
      NOTIFICATION_SEND_INTERVAL: ${NOTIFICATION_SEND_INTERVAL}
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.20.0.11
    ports:
      - "${RPC_PORT}:${RPC_PORT}"
      - "${BLOCKCHAIN_PORT}:${BLOCKCHAIN_PORT}"
      - "${P2P_PORT}:${P2P_PORT}"
