services:
  blockchain:
    image: bc:local
    environment:
      PORT: ${BLOCKCHAIN_PORT}
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      MULTICHAIN_RPC_USER: ${MULTICHAIN_RPC_USER}
      RPC_ALLOW_IP: ${RPC_ALLOW_IP}
      ORGANIZATION: ${ORGANIZATION}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      NODE_ENV: ${ENVIRONMENT}
      CERT_PATH: ${CERT_PATH}
      CERT_CA_PATH: ${CERT_CA_PATH}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
      BLOCKNOTIFY_SCRIPT: ${BLOCKNOTIFY_SCRIPT}
      KUBE_SERVICE_NAME: ${KUBE_SERVICE_NAME}
      KUBE_NAMESPACE: ${KUBE_NAMESPACE}
      EXPOSE_MC: ${EXPOSE_MC}
      CI_COMMIT_SHA: ${CI_COMMIT_SHA}
      BUILDTIMESTAMP: ${BUILDTIMESTAMP}
      EXTERNAL_IP: ${EXTERNAL_IP}
      MULTICHAIN_DIR: ${MULTICHAIN_DIR}
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.20.0.11
    ports:
      - "${MULTICHAIN_RPC_PORT}:${MULTICHAIN_RPC_PORT}"
      - "${BLOCKCHAIN_PORT}:${BLOCKCHAIN_PORT}"
      - "${P2P_PORT}:${P2P_PORT}"
