# Change ~/masterVolume to the location where the .multichain content should be saved on your machine 
version: "3"
services:
  blockchain:
    extends:
      file: blockchain/docker-compose.yml
      service: blockchain
    volumes:
      - ~/masterVolume:${MULTICHAIN_DIR}/.multichain
